In [199]:
import pandas as pd
import os
import numpy as np
import xgboost as xgb

In [213]:
os.chdir("C:\\Users\\chanqun\\Downloads\\ops")

In [205]:
df = pd.read_csv('Regular_Season_Batter.csv')
df_16 = df[df['year'] == 2016]
df_17 = df[df['year'] == 2017]

,batter_id,batter_name,year,team,avg,G,AB,R,H,2B,...,GDP,SLG,OBP,E,height/weight,year_born,position,career,starting_salary,OPS
5,1,강경학,2017,한화,0.214,59,84,17,18,2,...,1,0.262000,0.290000,4,180cm/72kg,1992년 08월 11일,내야수(우투좌타),광주대성초-광주동성중-광주동성고,10000만원,0.552000
10,2,강구성,2017,NC,0.000,1,1,0,0,0,...,0,0.000000,0.000000,0,180cm/82kg,1993년 06월 09일,외야수(우투좌타),관산초-부천중-야탑고-NC-상무,9000만원,0.000000
55,4,강민호,2017,롯데,0.285,130,456,62,130,22,...,15,0.482000,0.361000,11,185cm/100kg,1985년 08월 18일,포수(우투우타),제주신광초-포철중-포철공고-(국제디지털대)-롯데,9000만원,0.843000
84,8,강상원,2017,한화,0.214,33,14,8,3,1,...,0,0.286000,0.214000,0,172cm/64kg,1997년 05월 05일,외야수(우투좌타),온양온천초-온양중-북일고,3000만원,0.500000
87,9,강승호,2017,LG,0.250,85,248,42,62,14,...,5,0.383000,0.272000,12,179cm/77kg,1994년 02월 09일,내야수(우투우타),순천북초-천안북중-북일고-LG-경찰-LG,20000만원,0.655000
99,11,강진성,2017,NC,0.296,28,27,5,8,3,...,1,0.519000,0.406000,0,180cm/81kg,1993년 10월 19일,내야수(우투우타),가동초-잠신중-경기고-NC-경찰,7000만원,0.925000
104,12,강한울,2017,삼성,0.303,135,412,58,125,9,...,4,0.340000,0.344000,16,181cm/66kg,1991년 09월 12일,내야수(우투좌타),사당초-중앙중-안산공고-원광대-KIA,14000만원,0.684000
140,230,이종환,2017,한화,0.000,1,2,0,0,0,...,0,0.000000,0.000000,0,NaN,1986년 05월 08일,NaN,태안초-태안중-북일고-단국대-KIA-상무-KIA,NaN,0.000000
145,18,고종욱,2017,넥센,0.312,123,426,70,133,24,...,11,0.462000,0.349000,5,184cm/83kg,1989년 01월 11일,외야수(우투좌타),역삼초-대치중-경기고-한양대-넥센-상무,8000만원,0.811000
149,19,구자욱,2017,삼성,0.310,144,564,108,175,39,...,1,0.527000,0.383000,5,189cm/75kg,1993년 02월 12일,외야수(우투좌타),본리초-경복중-대구고-삼성-상무,13000만원,0.910000
154,20,국해성,2017,두산,0.209,57,86,15,18,3,...,2,0.349000,0.281000,0,180cm/94kg,1989년 10월 08일,외야수(우투양타),군산중앙초-동인천중-인천고,NaN,0.630000
193,22,권정웅,2017,삼성,0.212,61,99,11,21,3,...,4,0.424000,0.278000,1,180cm/88kg,1992년 11월 15일,포수(우투우타),서울이수초-영동중-덕수고-한양대,6000만원,0.702000
198,23,권희동,2017,NC,0.286,141,472,72,135,20,...,12,0.458000,0.371000,3,177cm/85kg,1990년 12월 30일,외야수(우투우타),동천초-경주중-경주고-경남대-NC-상무,3000만원,0.829000
215,24,김강민,2017,SK,0.219,88,183,31,40,5,...,3,0.339000,0.296000,2,182cm/85kg,1982년 09월 13일,외야수(우투우타),본리초-대구중-경북고,11000만원,0.635000
234,26,김경언,2017,한화,0.248,38,105,17,26,7,...,1,0.457143,0.330508,0,NaN,1982년 12월 07일,NaN,부산중앙초-개성중-경남상고-KIA,NaN,0.787651
237,28,김규민,2017,넥센,0.238,14,21,5,5,0,...,0,0.333000,0.304000,1,188cm/85kg,1993년 01월 26일,외야수(좌투좌타),일산초-자양중-휘문고,5000만원,0.637000
254,29,김대륙,2017,롯데,0.151,50,53,4,8,2,...,0,0.188679,0.210526,4,NaN,1992년 04월 03일,NaN,대해초-포철중-포철공고-동아대,NaN,0.399206
260,101,문선재,2017,LG,0.261,35,92,17,24,6,...,0,0.413000,0.333000,3,184cm/80kg,1990년 05월 20일,외야수(우투우타),광주서림초-광주동성중-광주동성고-LG-상무,5000만원,0.746000
263,30,김동엽,2017,SK,0.277,125,393,58,109,18,...,6,0.496000,0.329000,5,186cm/101kg,1990년 07월 24일,외야수(우투우타),천안남산초-천안북중-북일고,NaN,0.825000
270,31,김동욱,2017,KT,0.287,83,209,28,60,9,...,7,0.388000,0.309000,4,183cm/89kg,1988년 06월 24일,내야수(우투우타),신광초-경복중-대구고-삼성,13000만원,0.697000
291,33,김동한,2017,롯데,0.236,81,178,26,42,19,...,2,0.393000,0.292000,7,174cm/74kg,1988년 06월 24일,내야수(우투우타),내발산초-양천중-장충고-동국대-두산-상무-두산,4000만원,0.685000
294,34,김만수,2017,KT,0.167,10,6,0,1,0,...,0,0.167000,0.167000,1,180cm/80kg,1996년 04월 18일,포수(우투우타),순천북초-순천이수중-효천고,7000만원,0.334000
304,35,김문호,2017,롯데,0.292,131,390,49,114,17,...,5,0.356000,0.372000,4,185cm/102kg,1987년 06월 22일,외야수(좌투좌타),고명초-덕수중-덕수정보고-(영남사이버대)-롯데-상무,12000만원,0.728000
316,36,김민성,2017,넥센,0.282,133,472,59,133,26,...,15,0.436000,0.345000,6,181cm/94kg,1988년 12월 17일,내야수(우투우타),고명초-잠신중-덕수정보고-(영남사이버대)-롯데,10000만원,0.781000
319,37,김민수,2017,삼성,0.143,13,21,2,3,1,...,0,0.190000,0.182000,1,177cm/80kg,1991년 03월 02일,포수(우투우타),대구옥산초-경복중-대구상원고-영남대-한화-삼성-상무,11000만원,0.372000
323,38,김민식,2017,KIA,0.222,137,352,39,78,9,...,7,0.293000,0.283000,8,180cm/80kg,1989년 06월 28일,포수(우투좌타),양덕초-마산중-마산고-원광대-SK-상무-SK,14000만원,0.576000
328,335,홍성갑,2017,넥센,0.143,7,7,0,1,0,...,1,0.143000,0.250000,0,181cm/80kg,1992년 08월 02일,외야수(우투우타),서원초-천안북중-북일고,NaN,0.393000
339,40,김사훈,2017,롯데,0.184,57,76,1,14,3,...,2,0.224000,0.250000,1,173cm/89kg,1987년 06월 18일,포수(우투우타),감천초-대신중-부산고-한민대-롯데-경찰,NaN,0.474000
349,41,김상수,2017,삼성,0.264,42,144,17,38,7,...,4,0.375000,0.291000,7,175cm/68kg,1990년 03월 23일,내야수(우투우타),대구옥산초-경복중-경북고,28000만원,0.666000
359,42,김상호,2017,롯데,0.228,80,101,7,23,3,...,4,0.277000,0.316000,0,181cm/87kg,1989년 05월 10일,내야수(우투우타),청구초-홍은중-장충고-고려대-롯데-상무,3000만원,0.593000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2122,293,주효상,2017,넥센,0.195,64,118,10,23,5,...,2,0.263000,0.264000,2,182cm/85kg,1997년 11월 11일,포수(우투좌타),역북초-강남중-서울고,20000만원,0.527000
2135,294,지석훈,2017,NC,0.239,121,268,29,64,16,...,8,0.366000,0.318000,11,181cm/74kg,1984년 03월 17일,내야수(우투우타),가동초-휘문중-휘문고-현대-우리-상무-넥센,25000만원,0.684000
2156,298,차일목,2017,한화,0.207,52,92,7,19,3,...,5,0.271739,0.324074,0,NaN,1981년 01월 26일,NaN,본리초-경운중-대구상고-홍익대-KIA-한화,NaN,0.595813
2169,300,채은성,2017,LG,0.267,114,333,28,89,12,...,8,0.339000,0.323000,3,186cm/92kg,1990년 02월 06일,외야수(우투우타),순천북초-순천이수중-효천고,NaN,0.662000
2181,301,채태인,2017,넥센,0.322,109,342,46,110,23,...,9,0.500000,0.388000,6,187cm/94kg,1982년 10월 11일,내야수(좌투좌타),대신초-대동중-부산상고-삼성-넥센,10000만원,0.888000
2183,302,초이스,2017,넥센,0.307,46,176,37,54,8,...,5,0.653000,0.388000,1,183cm/98kg,1989년 11월 10일,외야수(우투우타),미국 Texas at Arlington(대),NaN,1.041000
2195,303,최경철,2017,삼성,0.313,25,32,5,10,2,...,0,0.562500,0.421053,0,NaN,1980년 08월 15일,NaN,효자초-전주동중-전주고-동의대-SK-상무-SK-넥센-LG,NaN,0.983553
2224,307,최승준,2017,SK,0.233,31,90,11,21,4,...,3,0.478000,0.296000,1,188cm/88kg,1988년 01월 11일,내야수(우투우타),인천서림초-동산중-동산고-LG,5000만원,0.774000
2230,308,최영진,2017,삼성,0.200,14,20,4,4,0,...,0,0.550000,0.238000,1,185cm/87kg,1988년 05월 10일,내야수(우투우타),영랑초-설악중-속초상고-한일장신대-LG-두산,NaN,0.788000
2234,309,최원제,2017,삼성,0.222,11,18,3,4,3,...,1,0.389000,0.222000,0,183cm/95kg,1989년 02월 04일,내야수(우투좌타),사당초-이수중-장충고-삼성-경찰,25000만원,0.611000
2237,310,최원준,2017,KIA,0.308,72,156,27,48,15,...,2,0.462000,0.351000,6,178cm/85kg,1997년 03월 23일,내야수(우투좌타),연현초-서울경원중-서울고,15000만원,0.813000
2244,311,최윤석,2017,한화,0.219,21,32,3,7,0,...,0,0.219000,0.219000,1,175cm/75kg,1987년 03월 28일,내야수(우투우타),화곡초-덕수중-성남고-홍익대-SK-한화-경찰,6000만원,0.438000
2252,312,최재훈,2017,한화,0.257,104,269,22,69,10,...,10,0.305000,0.340000,1,178cm/76kg,1989년 08월 27일,포수(우투우타),화곡초-덕수중-덕수고-(방송통신대)-두산-경찰-두산,NaN,0.645000
2266,313,최정,2017,SK,0.316,130,430,89,136,18,...,8,0.684000,0.427000,6,180cm/90kg,1987년 02월 28일,내야수(우투우타),대일초-평촌중-유신고,30000만원,1.111000
2271,314,최정민,2017,KIA,0.333,8,9,1,3,1,...,0,0.444000,0.333000,0,177cm/75kg,1989년 06월 02일,내야수(우투좌타),배영초-마산중-마산고-동아대-SK-상무-SK,6000만원,0.777000
2282,315,최주환,2017,두산,0.301,129,399,65,120,16,...,10,0.424000,0.370000,7,178cm/73kg,1988년 02월 28일,내야수(우투좌타),학강초-광주동성중-광주동성고-두산-상무,6000만원,0.794000
2298,316,최준석,2017,롯데,0.291,125,409,43,119,15,...,24,0.430000,0.364000,1,187cm/130kg,1983년 02월 15일,내야수(우투우타),칠성초-포철중-포철공고-(영남사이버대)-롯데-두산-롯데,3000만원,0.794000
2311,317,최진행,2017,한화,0.306,89,258,29,79,21,...,3,0.539000,0.375000,1,188cm/100kg,1985년 08월 17일,외야수(우투우타),서울동원초-청량중-덕수정보고-(우송대)-한화-경찰,10000만원,0.914000
2313,318,최항,2017,SK,0.321,37,106,14,34,8,...,1,0.425000,0.351000,3,183cm/88kg,1994년 01월 03일,내야수(우투좌타),대일초-매송중-유신고,NaN,0.776000
2326,319,최형우,2017,KIA,0.342,142,514,98,176,36,...,15,0.576000,0.450000,4,180cm/106kg,1983년 12월 16일,외야수(우투좌타),진북초-전주동중-전주고-삼성-경찰-삼성,5000만원,1.026000
2343,324,하주석,2017,한화,0.285,111,432,69,123,18,...,6,0.440000,0.328000,9,184cm/84kg,1994년 02월 25일,내야수(우투좌타),강남초-덕수중-신일고-한화-상무,30000만원,0.768000
2349,325,하준호,2017,KT,0.224,101,196,31,44,11,...,3,0.337000,0.311000,8,174cm/78kg,1989년 04월 29일,외야수(좌투좌타),하단초-대동중-경남고-롯데,16000만원,0.648000
2355,326,한동민,2017,SK,0.294,103,350,64,103,21,...,8,0.614000,0.396000,5,190cm/95kg,1989년 08월 09일,외야수(우투좌타),중앙초(해운대리틀)-대천중-경남고-경성대-SK-상무,3000만원,1.010000
2360,329,한승택,2017,KIA,0.229,96,83,7,19,2,...,1,0.277000,0.289000,2,174cm/83kg,1994년 06월 21일,포수(우투우타),잠전초(남양주리틀)-잠신중-덕수고-한화-경찰,9000만원,0.566000
2371,331,허경민,2017,두산,0.257,130,369,50,95,22,...,15,0.347000,0.327000,5,176cm/69kg,1990년 08월 26일,내야수(우투우타),송정동초-충장중-광주제일고-두산-경찰,13000만원,0.674000
2380,332,허도환,2017,한화,0.225,30,40,4,9,3,...,2,0.375000,0.326000,0,176cm/87kg,1984년 07월 31일,포수(우투우타),서울학동초-이수중-서울고-단국대-두산-넥센-한화,NaN,0.701000
2416,337,홍재호,2017,KIA,NaN,2,0,0,0,0,...,0,NaN,NaN,0,180cm/79kg,1987년 05월 10일,내야수(우투우타),부산대연초-대천중-부산고-고려대-KIA-경찰,4000만원,NaN
2423,339,황목치승,2017,LG,0.207,45,29,14,6,0,...,0,0.206897,0.258065,4,NaN,1985년 06월 21일,NaN,제주남초-제주제일중-일본 교토고쿠사이고-일본 아세아대,NaN,0.464961
2432,341,황윤호,2017,NC,0.133,36,15,8,2,0,...,0,0.267000,0.235000,1,177cm/78kg,1993년 09월 22일,내야수(우투우타),수주초-신월중-장충고-NC-경찰-NC,3000만원,0.502000
2452,344,황진수,2017,롯데,0.291,60,117,18,34,6,...,2,0.402000,0.359000,4,181cm/82kg,1989년 02월 15일,내야수(우투양타),석천초-대헌중-공주고,4000만원,0.761000

In [219]:
df_1617 = pd.merge(df_16, df_17, on = 'batter_id', how = 'inner') 
# df_16.to_csv('out16.csv')
# df_17.to_csv('out17.csv')
df_1617

,batter_id,batter_name_x,year_x,team_x,avg_x,G_x,AB_x,R_x,H_x,2B_x,...,GDP_y,SLG_y,OBP_y,E_y,height/weight_y,year_born_y,position_y,career_y,starting_salary_y,OPS_y
0,1,강경학,2016,한화,0.158,46,101,16,16,3,...,1,0.262000,0.290000,4,180cm/72kg,1992년 08월 11일,내야수(우투좌타),광주대성초-광주동성중-광주동성고,10000만원,0.552000
1,2,강구성,2016,NC,0.000,2,3,0,0,0,...,0,0.000000,0.000000,0,180cm/82kg,1993년 06월 09일,외야수(우투좌타),관산초-부천중-야탑고-NC-상무,9000만원,0.000000
2,4,강민호,2016,롯데,0.323,116,381,65,123,26,...,15,0.482000,0.361000,11,185cm/100kg,1985년 08월 18일,포수(우투우타),제주신광초-포철중-포철공고-(국제디지털대)-롯데,9000만원,0.843000
3,9,강승호,2016,LG,0.184,18,38,4,7,3,...,5,0.383000,0.272000,12,179cm/77kg,1994년 02월 09일,내야수(우투우타),순천북초-천안북중-북일고-LG-경찰-LG,20000만원,0.655000
4,12,강한울,2016,KIA,0.272,104,298,36,81,13,...,4,0.340000,0.344000,16,181cm/66kg,1991년 09월 12일,내야수(우투좌타),사당초-중앙중-안산공고-원광대-KIA,14000만원,0.684000
5,230,이종환,2016,한화,0.276,31,29,3,8,1,...,0,0.000000,0.000000,0,NaN,1986년 05월 08일,NaN,태안초-태안중-북일고-단국대-KIA-상무-KIA,NaN,0.000000
6,18,고종욱,2016,넥센,0.334,133,527,92,176,22,...,11,0.462000,0.349000,5,184cm/83kg,1989년 01월 11일,외야수(우투좌타),역삼초-대치중-경기고-한양대-넥센-상무,8000만원,0.811000
7,19,구자욱,2016,삼성,0.343,108,428,105,147,19,...,1,0.527000,0.383000,5,189cm/75kg,1993년 02월 12일,외야수(우투좌타),본리초-경복중-대구고-삼성-상무,13000만원,0.910000
8,20,국해성,2016,두산,0.278,58,151,28,42,11,...,2,0.349000,0.281000,0,180cm/94kg,1989년 10월 08일,외야수(우투양타),군산중앙초-동인천중-인천고,NaN,0.630000
9,22,권정웅,2016,삼성,1.000,3,1,1,1,0,...,4,0.424000,0.278000,1,180cm/88kg,1992년 11월 15일,포수(우투우타),서울이수초-영동중-덕수고-한양대,6000만원,0.702000
10,23,권희동,2016,NC,0.268,14,41,4,11,0,...,12,0.458000,0.371000,3,177cm/85kg,1990년 12월 30일,외야수(우투우타),동천초-경주중-경주고-경남대-NC-상무,3000만원,0.829000
11,24,김강민,2016,SK,0.298,115,366,59,109,21,...,3,0.339000,0.296000,2,182cm/85kg,1982년 09월 13일,외야수(우투우타),본리초-대구중-경북고,11000만원,0.635000
12,26,김경언,2016,한화,0.264,66,182,23,48,6,...,1,0.457143,0.330508,0,NaN,1982년 12월 07일,NaN,부산중앙초-개성중-경남상고-KIA,NaN,0.787651
13,29,김대륙,2016,롯데,0.143,58,49,5,7,1,...,0,0.188679,0.210526,4,NaN,1992년 04월 03일,NaN,대해초-포철중-포철공고-동아대,NaN,0.399206
14,101,문선재,2016,LG,0.288,52,111,28,32,3,...,0,0.413000,0.333000,3,184cm/80kg,1990년 05월 20일,외야수(우투우타),광주서림초-광주동성중-광주동성고-LG-상무,5000만원,0.746000
15,30,김동엽,2016,SK,0.336,57,143,19,48,8,...,6,0.496000,0.329000,5,186cm/101kg,1990년 07월 24일,외야수(우투우타),천안남산초-천안북중-북일고,NaN,0.825000
16,31,김동욱,2016,KT,0.135,21,37,3,5,0,...,7,0.388000,0.309000,4,183cm/89kg,1988년 06월 24일,내야수(우투우타),신광초-경복중-대구고-삼성,13000만원,0.697000
17,33,김동한,2016,롯데,0.252,78,107,9,27,6,...,2,0.393000,0.292000,7,174cm/74kg,1988년 06월 24일,내야수(우투우타),내발산초-양천중-장충고-동국대-두산-상무-두산,4000만원,0.685000
18,34,김만수,2016,KT,0.000,1,1,0,0,0,...,0,0.167000,0.167000,1,180cm/80kg,1996년 04월 18일,포수(우투우타),순천북초-순천이수중-효천고,7000만원,0.334000
19,35,김문호,2016,롯데,0.325,140,526,77,171,28,...,5,0.356000,0.372000,4,185cm/102kg,1987년 06월 22일,외야수(좌투좌타),고명초-덕수중-덕수정보고-(영남사이버대)-롯데-상무,12000만원,0.728000
20,36,김민성,2016,넥센,0.306,141,510,76,156,39,...,15,0.436000,0.345000,6,181cm/94kg,1988년 12월 17일,내야수(우투우타),고명초-잠신중-덕수정보고-(영남사이버대)-롯데,10000만원,0.781000
21,38,김민식,2016,SK,0.257,88,144,17,37,9,...,7,0.293000,0.283000,8,180cm/80kg,1989년 06월 28일,포수(우투좌타),양덕초-마산중-마산고-원광대-SK-상무-SK,14000만원,0.576000
22,335,홍성갑,2016,넥센,0.226,44,62,4,14,0,...,1,0.143000,0.250000,0,181cm/80kg,1992년 08월 02일,외야수(우투우타),서원초-천안북중-북일고,NaN,0.393000
23,40,김사훈,2016,롯데,0.321,19,28,5,9,1,...,2,0.224000,0.250000,1,173cm/89kg,1987년 06월 18일,포수(우투우타),감천초-대신중-부산고-한민대-롯데-경찰,NaN,0.474000
24,41,김상수,2016,삼성,0.271,105,358,56,97,13,...,4,0.375000,0.291000,7,175cm/68kg,1990년 03월 23일,내야수(우투우타),대구옥산초-경복중-경북고,28000만원,0.666000
25,42,김상호,2016,롯데,0.290,114,366,39,106,20,...,4,0.277000,0.316000,0,181cm/87kg,1989년 05월 10일,내야수(우투우타),청구초-홍은중-장충고-고려대-롯데-상무,3000만원,0.593000
26,47,김연훈,2016,KT,0.217,103,166,13,36,10,...,0,0.250000,0.166667,1,NaN,1984년 12월 23일,NaN,군산초-군산남중-군산상고-성균관대-KIA-SK-KT,NaN,0.416667
27,43,김선빈,2016,KIA,0.360,6,25,3,9,2,...,10,0.477000,0.420000,14,165cm/77kg,1989년 12월 18일,내야수(우투우타),화순초-화순중-화순고-KIA-상무,3000만원,0.897000
28,44,김성욱,2016,NC,0.265,130,306,60,81,15,...,4,0.390000,0.315000,0,181cm/83kg,1993년 05월 01일,외야수(우투우타),광주서림초-충장중-진흥고,7000만원,0.705000
29,45,김성현,2016,SK,0.319,138,479,66,153,28,...,8,0.339000,0.335000,6,172cm/72kg,1987년 03월 09일,내야수(우투우타),송정동초-충장중-광주제일고-SK-상무,7000만원,0.674000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,286,조수행,2016,두산,0.276,66,29,16,8,0,...,0,0.319000,0.346000,1,178cm/73kg,1993년 08월 30일,외야수(우투좌타),노암초-경포중-강릉고-건국대,14000만원,0.665000
153,287,조영훈,2016,NC,0.335,109,179,29,60,14,...,2,0.275000,0.244444,1,NaN,1982년 11월 12일,NaN,영랑초-설악중-속초상고-건국대-삼성-경찰-삼성-KIA,NaN,0.519444
154,288,조윤준,2016,LG,1.000,2,1,1,1,0,...,2,0.237000,0.268000,0,185cm/95kg,1989년 08월 30일,포수(우투우타),대전신흥초-한밭중-북일고-중앙대,20000만원,0.505000
155,289,조인성,2016,한화,0.168,76,137,10,23,2,...,1,0.137931,0.137931,2,NaN,1975년 05월 25일,NaN,수유초-신일중-신일고-연세대-LG-SK-한화,NaN,0.275862
156,293,주효상,2016,넥센,0.222,12,18,3,4,1,...,2,0.263000,0.264000,2,182cm/85kg,1997년 11월 11일,포수(우투좌타),역북초-강남중-서울고,20000만원,0.527000
157,294,지석훈,2016,NC,0.219,141,351,34,77,14,...,8,0.366000,0.318000,11,181cm/74kg,1984년 03월 17일,내야수(우투우타),가동초-휘문중-휘문고-현대-우리-상무-넥센,25000만원,0.684000
158,298,차일목,2016,한화,0.228,117,276,30,63,8,...,5,0.271739,0.324074,0,NaN,1981년 01월 26일,NaN,본리초-경운중-대구상고-홍익대-KIA-한화,NaN,0.595813
159,300,채은성,2016,LG,0.313,128,403,64,126,20,...,8,0.339000,0.323000,3,186cm/92kg,1990년 02월 06일,외야수(우투우타),순천북초-순천이수중-효천고,NaN,0.662000
160,301,채태인,2016,넥센,0.286,124,370,29,106,14,...,9,0.500000,0.388000,6,187cm/94kg,1982년 10월 11일,내야수(좌투좌타),대신초-대동중-부산상고-삼성-넥센,10000만원,0.888000
161,303,최경철,2016,LG,0.156,29,45,3,7,2,...,0,0.562500,0.421053,0,NaN,1980년 08월 15일,NaN,효자초-전주동중-전주고-동의대-SK-상무-SK-넥센-LG,NaN,0.983553
162,307,최승준,2016,SK,0.266,76,199,31,53,5,...,3,0.478000,0.296000,1,188cm/88kg,1988년 01월 11일,내야수(우투우타),인천서림초-동산중-동산고-LG,5000만원,0.774000
163,310,최원준,2016,KIA,0.458,14,24,5,11,1,...,2,0.462000,0.351000,6,178cm/85kg,1997년 03월 23일,내야수(우투좌타),연현초-서울경원중-서울고,15000만원,0.813000
164,311,최윤석,2016,한화,0.125,11,16,2,2,0,...,0,0.219000,0.219000,1,175cm/75kg,1987년 03월 28일,내야수(우투우타),화곡초-덕수중-성남고-홍익대-SK-한화-경찰,6000만원,0.438000
165,312,최재훈,2016,두산,0.167,22,18,1,3,1,...,10,0.305000,0.340000,1,178cm/76kg,1989년 08월 27일,포수(우투우타),화곡초-덕수중-덕수고-(방송통신대)-두산-경찰-두산,NaN,0.645000
166,313,최정,2016,SK,0.288,141,500,106,144,24,...,8,0.684000,0.427000,6,180cm/90kg,1987년 02월 28일,내야수(우투우타),대일초-평촌중-유신고,30000만원,1.111000
167,314,최정민,2016,SK,0.329,88,155,29,51,4,...,0,0.444000,0.333000,0,177cm/75kg,1989년 06월 02일,내야수(우투좌타),배영초-마산중-마산고-동아대-SK-상무-SK,6000만원,0.777000
168,315,최주환,2016,두산,0.281,85,160,21,45,11,...,10,0.424000,0.370000,7,178cm/73kg,1988년 02월 28일,내야수(우투좌타),학강초-광주동성중-광주동성고-두산-상무,6000만원,0.794000
169,316,최준석,2016,롯데,0.262,116,325,49,85,10,...,24,0.430000,0.364000,1,187cm/130kg,1983년 02월 15일,내야수(우투우타),칠성초-포철중-포철공고-(영남사이버대)-롯데-두산-롯데,3000만원,0.794000
170,317,최진행,2016,한화,0.329,28,70,4,23,2,...,3,0.539000,0.375000,1,188cm/100kg,1985년 08월 17일,외야수(우투우타),서울동원초-청량중-덕수정보고-(우송대)-한화-경찰,10000만원,0.914000
171,319,최형우,2016,삼성,0.376,138,519,99,195,46,...,15,0.576000,0.450000,4,180cm/106kg,1983년 12월 16일,외야수(우투좌타),진북초-전주동중-전주고-삼성-경찰-삼성,5000만원,1.026000
172,324,하주석,2016,한화,0.279,115,405,58,113,21,...,6,0.440000,0.328000,9,184cm/84kg,1994년 02월 25일,내야수(우투좌타),강남초-덕수중-신일고-한화-상무,30000만원,0.768000
173,325,하준호,2016,KT,0.219,94,187,26,41,5,...,3,0.337000,0.311000,8,174cm/78kg,1989년 04월 29일,외야수(좌투좌타),하단초-대동중-경남고-롯데,16000만원,0.648000
174,326,한동민,2016,SK,0.278,6,18,3,5,0,...,8,0.614000,0.396000,5,190cm/95kg,1989년 08월 09일,외야수(우투좌타),중앙초(해운대리틀)-대천중-경남고-경성대-SK-상무,3000만원,1.010000
175,329,한승택,2016,KIA,0.179,27,28,1,5,0,...,1,0.277000,0.289000,2,174cm/83kg,1994년 06월 21일,포수(우투우타),잠전초(남양주리틀)-잠신중-덕수고-한화-경찰,9000만원,0.566000
176,331,허경민,2016,두산,0.286,144,538,96,154,24,...,15,0.347000,0.327000,5,176cm/69kg,1990년 08월 26일,내야수(우투우타),송정동초-충장중-광주제일고-두산-경찰,13000만원,0.674000
177,332,허도환,2016,한화,0.218,48,78,9,17,8,...,2,0.375000,0.326000,0,176cm/87kg,1984년 07월 31일,포수(우투우타),서울학동초-이수중-서울고-단국대-두산-넥센-한화,NaN,0.701000
178,337,홍재호,2016,KIA,0.077,22,13,4,1,0,...,0,NaN,NaN,0,180cm/79kg,1987년 05월 10일,내야수(우투우타),부산대연초-대천중-부산고-고려대-KIA-경찰,4000만원,NaN
179,339,황목치승,2016,LG,0.179,48,39,7,7,3,...,0,0.206897,0.258065,4,NaN,1985년 06월 21일,NaN,제주남초-제주제일중-일본 교토고쿠사이고-일본 아세아대,NaN,0.464961
180,341,황윤호,2016,NC,0.083,33,12,7,1,0,...,0,0.267000,0.235000,1,177cm/78kg,1993년 09월 22일,내야수(우투우타),수주초-신월중-장충고-NC-경찰-NC,3000만원,0.502000
181,344,황진수,2016,롯데,0.000,11,10,2,0,0,...,2,0.402000,0.359000,4,181cm/82kg,1989년 02월 15일,내야수(우투양타),석천초-대헌중-공주고,4000만원,0.761000

In [224]:
df_16_1 = df_1617[df_1617['year_x'] == 2016]

In [225]:
df_16_1

,batter_id,batter_name_x,year_x,team_x,avg_x,G_x,AB_x,R_x,H_x,2B_x,...,GDP_y,SLG_y,OBP_y,E_y,height/weight_y,year_born_y,position_y,career_y,starting_salary_y,OPS_y
0,1,강경학,2016,한화,0.158,46,101,16,16,3,...,1,0.262000,0.290000,4,180cm/72kg,1992년 08월 11일,내야수(우투좌타),광주대성초-광주동성중-광주동성고,10000만원,0.552000
1,2,강구성,2016,NC,0.000,2,3,0,0,0,...,0,0.000000,0.000000,0,180cm/82kg,1993년 06월 09일,외야수(우투좌타),관산초-부천중-야탑고-NC-상무,9000만원,0.000000
2,4,강민호,2016,롯데,0.323,116,381,65,123,26,...,15,0.482000,0.361000,11,185cm/100kg,1985년 08월 18일,포수(우투우타),제주신광초-포철중-포철공고-(국제디지털대)-롯데,9000만원,0.843000
3,9,강승호,2016,LG,0.184,18,38,4,7,3,...,5,0.383000,0.272000,12,179cm/77kg,1994년 02월 09일,내야수(우투우타),순천북초-천안북중-북일고-LG-경찰-LG,20000만원,0.655000
4,12,강한울,2016,KIA,0.272,104,298,36,81,13,...,4,0.340000,0.344000,16,181cm/66kg,1991년 09월 12일,내야수(우투좌타),사당초-중앙중-안산공고-원광대-KIA,14000만원,0.684000
5,230,이종환,2016,한화,0.276,31,29,3,8,1,...,0,0.000000,0.000000,0,NaN,1986년 05월 08일,NaN,태안초-태안중-북일고-단국대-KIA-상무-KIA,NaN,0.000000
6,18,고종욱,2016,넥센,0.334,133,527,92,176,22,...,11,0.462000,0.349000,5,184cm/83kg,1989년 01월 11일,외야수(우투좌타),역삼초-대치중-경기고-한양대-넥센-상무,8000만원,0.811000
7,19,구자욱,2016,삼성,0.343,108,428,105,147,19,...,1,0.527000,0.383000,5,189cm/75kg,1993년 02월 12일,외야수(우투좌타),본리초-경복중-대구고-삼성-상무,13000만원,0.910000
8,20,국해성,2016,두산,0.278,58,151,28,42,11,...,2,0.349000,0.281000,0,180cm/94kg,1989년 10월 08일,외야수(우투양타),군산중앙초-동인천중-인천고,NaN,0.630000
9,22,권정웅,2016,삼성,1.000,3,1,1,1,0,...,4,0.424000,0.278000,1,180cm/88kg,1992년 11월 15일,포수(우투우타),서울이수초-영동중-덕수고-한양대,6000만원,0.702000
10,23,권희동,2016,NC,0.268,14,41,4,11,0,...,12,0.458000,0.371000,3,177cm/85kg,1990년 12월 30일,외야수(우투우타),동천초-경주중-경주고-경남대-NC-상무,3000만원,0.829000
11,24,김강민,2016,SK,0.298,115,366,59,109,21,...,3,0.339000,0.296000,2,182cm/85kg,1982년 09월 13일,외야수(우투우타),본리초-대구중-경북고,11000만원,0.635000
12,26,김경언,2016,한화,0.264,66,182,23,48,6,...,1,0.457143,0.330508,0,NaN,1982년 12월 07일,NaN,부산중앙초-개성중-경남상고-KIA,NaN,0.787651
13,29,김대륙,2016,롯데,0.143,58,49,5,7,1,...,0,0.188679,0.210526,4,NaN,1992년 04월 03일,NaN,대해초-포철중-포철공고-동아대,NaN,0.399206
14,101,문선재,2016,LG,0.288,52,111,28,32,3,...,0,0.413000,0.333000,3,184cm/80kg,1990년 05월 20일,외야수(우투우타),광주서림초-광주동성중-광주동성고-LG-상무,5000만원,0.746000
15,30,김동엽,2016,SK,0.336,57,143,19,48,8,...,6,0.496000,0.329000,5,186cm/101kg,1990년 07월 24일,외야수(우투우타),천안남산초-천안북중-북일고,NaN,0.825000
16,31,김동욱,2016,KT,0.135,21,37,3,5,0,...,7,0.388000,0.309000,4,183cm/89kg,1988년 06월 24일,내야수(우투우타),신광초-경복중-대구고-삼성,13000만원,0.697000
17,33,김동한,2016,롯데,0.252,78,107,9,27,6,...,2,0.393000,0.292000,7,174cm/74kg,1988년 06월 24일,내야수(우투우타),내발산초-양천중-장충고-동국대-두산-상무-두산,4000만원,0.685000
18,34,김만수,2016,KT,0.000,1,1,0,0,0,...,0,0.167000,0.167000,1,180cm/80kg,1996년 04월 18일,포수(우투우타),순천북초-순천이수중-효천고,7000만원,0.334000
19,35,김문호,2016,롯데,0.325,140,526,77,171,28,...,5,0.356000,0.372000,4,185cm/102kg,1987년 06월 22일,외야수(좌투좌타),고명초-덕수중-덕수정보고-(영남사이버대)-롯데-상무,12000만원,0.728000
20,36,김민성,2016,넥센,0.306,141,510,76,156,39,...,15,0.436000,0.345000,6,181cm/94kg,1988년 12월 17일,내야수(우투우타),고명초-잠신중-덕수정보고-(영남사이버대)-롯데,10000만원,0.781000
21,38,김민식,2016,SK,0.257,88,144,17,37,9,...,7,0.293000,0.283000,8,180cm/80kg,1989년 06월 28일,포수(우투좌타),양덕초-마산중-마산고-원광대-SK-상무-SK,14000만원,0.576000
22,335,홍성갑,2016,넥센,0.226,44,62,4,14,0,...,1,0.143000,0.250000,0,181cm/80kg,1992년 08월 02일,외야수(우투우타),서원초-천안북중-북일고,NaN,0.393000
23,40,김사훈,2016,롯데,0.321,19,28,5,9,1,...,2,0.224000,0.250000,1,173cm/89kg,1987년 06월 18일,포수(우투우타),감천초-대신중-부산고-한민대-롯데-경찰,NaN,0.474000
24,41,김상수,2016,삼성,0.271,105,358,56,97,13,...,4,0.375000,0.291000,7,175cm/68kg,1990년 03월 23일,내야수(우투우타),대구옥산초-경복중-경북고,28000만원,0.666000
25,42,김상호,2016,롯데,0.290,114,366,39,106,20,...,4,0.277000,0.316000,0,181cm/87kg,1989년 05월 10일,내야수(우투우타),청구초-홍은중-장충고-고려대-롯데-상무,3000만원,0.593000
26,47,김연훈,2016,KT,0.217,103,166,13,36,10,...,0,0.250000,0.166667,1,NaN,1984년 12월 23일,NaN,군산초-군산남중-군산상고-성균관대-KIA-SK-KT,NaN,0.416667
27,43,김선빈,2016,KIA,0.360,6,25,3,9,2,...,10,0.477000,0.420000,14,165cm/77kg,1989년 12월 18일,내야수(우투우타),화순초-화순중-화순고-KIA-상무,3000만원,0.897000
28,44,김성욱,2016,NC,0.265,130,306,60,81,15,...,4,0.390000,0.315000,0,181cm/83kg,1993년 05월 01일,외야수(우투우타),광주서림초-충장중-진흥고,7000만원,0.705000
29,45,김성현,2016,SK,0.319,138,479,66,153,28,...,8,0.339000,0.335000,6,172cm/72kg,1987년 03월 09일,내야수(우투우타),송정동초-충장중-광주제일고-SK-상무,7000만원,0.674000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,286,조수행,2016,두산,0.276,66,29,16,8,0,...,0,0.319000,0.346000,1,178cm/73kg,1993년 08월 30일,외야수(우투좌타),노암초-경포중-강릉고-건국대,14000만원,0.665000
153,287,조영훈,2016,NC,0.335,109,179,29,60,14,...,2,0.275000,0.244444,1,NaN,1982년 11월 12일,NaN,영랑초-설악중-속초상고-건국대-삼성-경찰-삼성-KIA,NaN,0.519444
154,288,조윤준,2016,LG,1.000,2,1,1,1,0,...,2,0.237000,0.268000,0,185cm/95kg,1989년 08월 30일,포수(우투우타),대전신흥초-한밭중-북일고-중앙대,20000만원,0.505000
155,289,조인성,2016,한화,0.168,76,137,10,23,2,...,1,0.137931,0.137931,2,NaN,1975년 05월 25일,NaN,수유초-신일중-신일고-연세대-LG-SK-한화,NaN,0.275862
156,293,주효상,2016,넥센,0.222,12,18,3,4,1,...,2,0.263000,0.264000,2,182cm/85kg,1997년 11월 11일,포수(우투좌타),역북초-강남중-서울고,20000만원,0.527000
157,294,지석훈,2016,NC,0.219,141,351,34,77,14,...,8,0.366000,0.318000,11,181cm/74kg,1984년 03월 17일,내야수(우투우타),가동초-휘문중-휘문고-현대-우리-상무-넥센,25000만원,0.684000
158,298,차일목,2016,한화,0.228,117,276,30,63,8,...,5,0.271739,0.324074,0,NaN,1981년 01월 26일,NaN,본리초-경운중-대구상고-홍익대-KIA-한화,NaN,0.595813
159,300,채은성,2016,LG,0.313,128,403,64,126,20,...,8,0.339000,0.323000,3,186cm/92kg,1990년 02월 06일,외야수(우투우타),순천북초-순천이수중-효천고,NaN,0.662000
160,301,채태인,2016,넥센,0.286,124,370,29,106,14,...,9,0.500000,0.388000,6,187cm/94kg,1982년 10월 11일,내야수(좌투좌타),대신초-대동중-부산상고-삼성-넥센,10000만원,0.888000
161,303,최경철,2016,LG,0.156,29,45,3,7,2,...,0,0.562500,0.421053,0,NaN,1980년 08월 15일,NaN,효자초-전주동중-전주고-동의대-SK-상무-SK-넥센-LG,NaN,0.983553
162,307,최승준,2016,SK,0.266,76,199,31,53,5,...,3,0.478000,0.296000,1,188cm/88kg,1988년 01월 11일,내야수(우투우타),인천서림초-동산중-동산고-LG,5000만원,0.774000
163,310,최원준,2016,KIA,0.458,14,24,5,11,1,...,2,0.462000,0.351000,6,178cm/85kg,1997년 03월 23일,내야수(우투좌타),연현초-서울경원중-서울고,15000만원,0.813000
164,311,최윤석,2016,한화,0.125,11,16,2,2,0,...,0,0.219000,0.219000,1,175cm/75kg,1987년 03월 28일,내야수(우투우타),화곡초-덕수중-성남고-홍익대-SK-한화-경찰,6000만원,0.438000
165,312,최재훈,2016,두산,0.167,22,18,1,3,1,...,10,0.305000,0.340000,1,178cm/76kg,1989년 08월 27일,포수(우투우타),화곡초-덕수중-덕수고-(방송통신대)-두산-경찰-두산,NaN,0.645000
166,313,최정,2016,SK,0.288,141,500,106,144,24,...,8,0.684000,0.427000,6,180cm/90kg,1987년 02월 28일,내야수(우투우타),대일초-평촌중-유신고,30000만원,1.111000
167,314,최정민,2016,SK,0.329,88,155,29,51,4,...,0,0.444000,0.333000,0,177cm/75kg,1989년 06월 02일,내야수(우투좌타),배영초-마산중-마산고-동아대-SK-상무-SK,6000만원,0.777000
168,315,최주환,2016,두산,0.281,85,160,21,45,11,...,10,0.424000,0.370000,7,178cm/73kg,1988년 02월 28일,내야수(우투좌타),학강초-광주동성중-광주동성고-두산-상무,6000만원,0.794000
169,316,최준석,2016,롯데,0.262,116,325,49,85,10,...,24,0.430000,0.364000,1,187cm/130kg,1983년 02월 15일,내야수(우투우타),칠성초-포철중-포철공고-(영남사이버대)-롯데-두산-롯데,3000만원,0.794000
170,317,최진행,2016,한화,0.329,28,70,4,23,2,...,3,0.539000,0.375000,1,188cm/100kg,1985년 08월 17일,외야수(우투우타),서울동원초-청량중-덕수정보고-(우송대)-한화-경찰,10000만원,0.914000
171,319,최형우,2016,삼성,0.376,138,519,99,195,46,...,15,0.576000,0.450000,4,180cm/106kg,1983년 12월 16일,외야수(우투좌타),진북초-전주동중-전주고-삼성-경찰-삼성,5000만원,1.026000
172,324,하주석,2016,한화,0.279,115,405,58,113,21,...,6,0.440000,0.328000,9,184cm/84kg,1994년 02월 25일,내야수(우투좌타),강남초-덕수중-신일고-한화-상무,30000만원,0.768000
173,325,하준호,2016,KT,0.219,94,187,26,41,5,...,3,0.337000,0.311000,8,174cm/78kg,1989년 04월 29일,외야수(좌투좌타),하단초-대동중-경남고-롯데,16000만원,0.648000
174,326,한동민,2016,SK,0.278,6,18,3,5,0,...,8,0.614000,0.396000,5,190cm/95kg,1989년 08월 09일,외야수(우투좌타),중앙초(해운대리틀)-대천중-경남고-경성대-SK-상무,3000만원,1.010000
175,329,한승택,2016,KIA,0.179,27,28,1,5,0,...,1,0.277000,0.289000,2,174cm/83kg,1994년 06월 21일,포수(우투우타),잠전초(남양주리틀)-잠신중-덕수고-한화-경찰,9000만원,0.566000
176,331,허경민,2016,두산,0.286,144,538,96,154,24,...,15,0.347000,0.327000,5,176cm/69kg,1990년 08월 26일,내야수(우투우타),송정동초-충장중-광주제일고-두산-경찰,13000만원,0.674000
177,332,허도환,2016,한화,0.218,48,78,9,17,8,...,2,0.375000,0.326000,0,176cm/87kg,1984년 07월 31일,포수(우투우타),서울학동초-이수중-서울고-단국대-두산-넥센-한화,NaN,0.701000
178,337,홍재호,2016,KIA,0.077,22,13,4,1,0,...,0,NaN,NaN,0,180cm/79kg,1987년 05월 10일,내야수(우투우타),부산대연초-대천중-부산고-고려대-KIA-경찰,4000만원,NaN
179,339,황목치승,2016,LG,0.179,48,39,7,7,3,...,0,0.206897,0.258065,4,NaN,1985년 06월 21일,NaN,제주남초-제주제일중-일본 교토고쿠사이고-일본 아세아대,NaN,0.464961
180,341,황윤호,2016,NC,0.083,33,12,7,1,0,...,0,0.267000,0.235000,1,177cm/78kg,1993년 09월 22일,내야수(우투우타),수주초-신월중-장충고-NC-경찰-NC,3000만원,0.502000
181,344,황진수,2016,롯데,0.000,11,10,2,0,0,...,2,0.402000,0.359000,4,181cm/82kg,1989년 02월 15일,내야수(우투양타),석천초-대헌중-공주고,4000만원,0.761000

In [228]:
df_17_1 = df_1617[df_1617['year_y'] == 2017]

In [229]:
df_17_1

,batter_id,batter_name_x,year_x,team_x,avg_x,G_x,AB_x,R_x,H_x,2B_x,...,GDP_y,SLG_y,OBP_y,E_y,height/weight_y,year_born_y,position_y,career_y,starting_salary_y,OPS_y
0,1,강경학,2016,한화,0.158,46,101,16,16,3,...,1,0.262000,0.290000,4,180cm/72kg,1992년 08월 11일,내야수(우투좌타),광주대성초-광주동성중-광주동성고,10000만원,0.552000
1,2,강구성,2016,NC,0.000,2,3,0,0,0,...,0,0.000000,0.000000,0,180cm/82kg,1993년 06월 09일,외야수(우투좌타),관산초-부천중-야탑고-NC-상무,9000만원,0.000000
2,4,강민호,2016,롯데,0.323,116,381,65,123,26,...,15,0.482000,0.361000,11,185cm/100kg,1985년 08월 18일,포수(우투우타),제주신광초-포철중-포철공고-(국제디지털대)-롯데,9000만원,0.843000
3,9,강승호,2016,LG,0.184,18,38,4,7,3,...,5,0.383000,0.272000,12,179cm/77kg,1994년 02월 09일,내야수(우투우타),순천북초-천안북중-북일고-LG-경찰-LG,20000만원,0.655000
4,12,강한울,2016,KIA,0.272,104,298,36,81,13,...,4,0.340000,0.344000,16,181cm/66kg,1991년 09월 12일,내야수(우투좌타),사당초-중앙중-안산공고-원광대-KIA,14000만원,0.684000
5,230,이종환,2016,한화,0.276,31,29,3,8,1,...,0,0.000000,0.000000,0,NaN,1986년 05월 08일,NaN,태안초-태안중-북일고-단국대-KIA-상무-KIA,NaN,0.000000
6,18,고종욱,2016,넥센,0.334,133,527,92,176,22,...,11,0.462000,0.349000,5,184cm/83kg,1989년 01월 11일,외야수(우투좌타),역삼초-대치중-경기고-한양대-넥센-상무,8000만원,0.811000
7,19,구자욱,2016,삼성,0.343,108,428,105,147,19,...,1,0.527000,0.383000,5,189cm/75kg,1993년 02월 12일,외야수(우투좌타),본리초-경복중-대구고-삼성-상무,13000만원,0.910000
8,20,국해성,2016,두산,0.278,58,151,28,42,11,...,2,0.349000,0.281000,0,180cm/94kg,1989년 10월 08일,외야수(우투양타),군산중앙초-동인천중-인천고,NaN,0.630000
9,22,권정웅,2016,삼성,1.000,3,1,1,1,0,...,4,0.424000,0.278000,1,180cm/88kg,1992년 11월 15일,포수(우투우타),서울이수초-영동중-덕수고-한양대,6000만원,0.702000
10,23,권희동,2016,NC,0.268,14,41,4,11,0,...,12,0.458000,0.371000,3,177cm/85kg,1990년 12월 30일,외야수(우투우타),동천초-경주중-경주고-경남대-NC-상무,3000만원,0.829000
11,24,김강민,2016,SK,0.298,115,366,59,109,21,...,3,0.339000,0.296000,2,182cm/85kg,1982년 09월 13일,외야수(우투우타),본리초-대구중-경북고,11000만원,0.635000
12,26,김경언,2016,한화,0.264,66,182,23,48,6,...,1,0.457143,0.330508,0,NaN,1982년 12월 07일,NaN,부산중앙초-개성중-경남상고-KIA,NaN,0.787651
13,29,김대륙,2016,롯데,0.143,58,49,5,7,1,...,0,0.188679,0.210526,4,NaN,1992년 04월 03일,NaN,대해초-포철중-포철공고-동아대,NaN,0.399206
14,101,문선재,2016,LG,0.288,52,111,28,32,3,...,0,0.413000,0.333000,3,184cm/80kg,1990년 05월 20일,외야수(우투우타),광주서림초-광주동성중-광주동성고-LG-상무,5000만원,0.746000
15,30,김동엽,2016,SK,0.336,57,143,19,48,8,...,6,0.496000,0.329000,5,186cm/101kg,1990년 07월 24일,외야수(우투우타),천안남산초-천안북중-북일고,NaN,0.825000
16,31,김동욱,2016,KT,0.135,21,37,3,5,0,...,7,0.388000,0.309000,4,183cm/89kg,1988년 06월 24일,내야수(우투우타),신광초-경복중-대구고-삼성,13000만원,0.697000
17,33,김동한,2016,롯데,0.252,78,107,9,27,6,...,2,0.393000,0.292000,7,174cm/74kg,1988년 06월 24일,내야수(우투우타),내발산초-양천중-장충고-동국대-두산-상무-두산,4000만원,0.685000
18,34,김만수,2016,KT,0.000,1,1,0,0,0,...,0,0.167000,0.167000,1,180cm/80kg,1996년 04월 18일,포수(우투우타),순천북초-순천이수중-효천고,7000만원,0.334000
19,35,김문호,2016,롯데,0.325,140,526,77,171,28,...,5,0.356000,0.372000,4,185cm/102kg,1987년 06월 22일,외야수(좌투좌타),고명초-덕수중-덕수정보고-(영남사이버대)-롯데-상무,12000만원,0.728000
20,36,김민성,2016,넥센,0.306,141,510,76,156,39,...,15,0.436000,0.345000,6,181cm/94kg,1988년 12월 17일,내야수(우투우타),고명초-잠신중-덕수정보고-(영남사이버대)-롯데,10000만원,0.781000
21,38,김민식,2016,SK,0.257,88,144,17,37,9,...,7,0.293000,0.283000,8,180cm/80kg,1989년 06월 28일,포수(우투좌타),양덕초-마산중-마산고-원광대-SK-상무-SK,14000만원,0.576000
22,335,홍성갑,2016,넥센,0.226,44,62,4,14,0,...,1,0.143000,0.250000,0,181cm/80kg,1992년 08월 02일,외야수(우투우타),서원초-천안북중-북일고,NaN,0.393000
23,40,김사훈,2016,롯데,0.321,19,28,5,9,1,...,2,0.224000,0.250000,1,173cm/89kg,1987년 06월 18일,포수(우투우타),감천초-대신중-부산고-한민대-롯데-경찰,NaN,0.474000
24,41,김상수,2016,삼성,0.271,105,358,56,97,13,...,4,0.375000,0.291000,7,175cm/68kg,1990년 03월 23일,내야수(우투우타),대구옥산초-경복중-경북고,28000만원,0.666000
25,42,김상호,2016,롯데,0.290,114,366,39,106,20,...,4,0.277000,0.316000,0,181cm/87kg,1989년 05월 10일,내야수(우투우타),청구초-홍은중-장충고-고려대-롯데-상무,3000만원,0.593000
26,47,김연훈,2016,KT,0.217,103,166,13,36,10,...,0,0.250000,0.166667,1,NaN,1984년 12월 23일,NaN,군산초-군산남중-군산상고-성균관대-KIA-SK-KT,NaN,0.416667
27,43,김선빈,2016,KIA,0.360,6,25,3,9,2,...,10,0.477000,0.420000,14,165cm/77kg,1989년 12월 18일,내야수(우투우타),화순초-화순중-화순고-KIA-상무,3000만원,0.897000
28,44,김성욱,2016,NC,0.265,130,306,60,81,15,...,4,0.390000,0.315000,0,181cm/83kg,1993년 05월 01일,외야수(우투우타),광주서림초-충장중-진흥고,7000만원,0.705000
29,45,김성현,2016,SK,0.319,138,479,66,153,28,...,8,0.339000,0.335000,6,172cm/72kg,1987년 03월 09일,내야수(우투우타),송정동초-충장중-광주제일고-SK-상무,7000만원,0.674000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,286,조수행,2016,두산,0.276,66,29,16,8,0,...,0,0.319000,0.346000,1,178cm/73kg,1993년 08월 30일,외야수(우투좌타),노암초-경포중-강릉고-건국대,14000만원,0.665000
153,287,조영훈,2016,NC,0.335,109,179,29,60,14,...,2,0.275000,0.244444,1,NaN,1982년 11월 12일,NaN,영랑초-설악중-속초상고-건국대-삼성-경찰-삼성-KIA,NaN,0.519444
154,288,조윤준,2016,LG,1.000,2,1,1,1,0,...,2,0.237000,0.268000,0,185cm/95kg,1989년 08월 30일,포수(우투우타),대전신흥초-한밭중-북일고-중앙대,20000만원,0.505000
155,289,조인성,2016,한화,0.168,76,137,10,23,2,...,1,0.137931,0.137931,2,NaN,1975년 05월 25일,NaN,수유초-신일중-신일고-연세대-LG-SK-한화,NaN,0.275862
156,293,주효상,2016,넥센,0.222,12,18,3,4,1,...,2,0.263000,0.264000,2,182cm/85kg,1997년 11월 11일,포수(우투좌타),역북초-강남중-서울고,20000만원,0.527000
157,294,지석훈,2016,NC,0.219,141,351,34,77,14,...,8,0.366000,0.318000,11,181cm/74kg,1984년 03월 17일,내야수(우투우타),가동초-휘문중-휘문고-현대-우리-상무-넥센,25000만원,0.684000
158,298,차일목,2016,한화,0.228,117,276,30,63,8,...,5,0.271739,0.324074,0,NaN,1981년 01월 26일,NaN,본리초-경운중-대구상고-홍익대-KIA-한화,NaN,0.595813
159,300,채은성,2016,LG,0.313,128,403,64,126,20,...,8,0.339000,0.323000,3,186cm/92kg,1990년 02월 06일,외야수(우투우타),순천북초-순천이수중-효천고,NaN,0.662000
160,301,채태인,2016,넥센,0.286,124,370,29,106,14,...,9,0.500000,0.388000,6,187cm/94kg,1982년 10월 11일,내야수(좌투좌타),대신초-대동중-부산상고-삼성-넥센,10000만원,0.888000
161,303,최경철,2016,LG,0.156,29,45,3,7,2,...,0,0.562500,0.421053,0,NaN,1980년 08월 15일,NaN,효자초-전주동중-전주고-동의대-SK-상무-SK-넥센-LG,NaN,0.983553
162,307,최승준,2016,SK,0.266,76,199,31,53,5,...,3,0.478000,0.296000,1,188cm/88kg,1988년 01월 11일,내야수(우투우타),인천서림초-동산중-동산고-LG,5000만원,0.774000
163,310,최원준,2016,KIA,0.458,14,24,5,11,1,...,2,0.462000,0.351000,6,178cm/85kg,1997년 03월 23일,내야수(우투좌타),연현초-서울경원중-서울고,15000만원,0.813000
164,311,최윤석,2016,한화,0.125,11,16,2,2,0,...,0,0.219000,0.219000,1,175cm/75kg,1987년 03월 28일,내야수(우투우타),화곡초-덕수중-성남고-홍익대-SK-한화-경찰,6000만원,0.438000
165,312,최재훈,2016,두산,0.167,22,18,1,3,1,...,10,0.305000,0.340000,1,178cm/76kg,1989년 08월 27일,포수(우투우타),화곡초-덕수중-덕수고-(방송통신대)-두산-경찰-두산,NaN,0.645000
166,313,최정,2016,SK,0.288,141,500,106,144,24,...,8,0.684000,0.427000,6,180cm/90kg,1987년 02월 28일,내야수(우투우타),대일초-평촌중-유신고,30000만원,1.111000
167,314,최정민,2016,SK,0.329,88,155,29,51,4,...,0,0.444000,0.333000,0,177cm/75kg,1989년 06월 02일,내야수(우투좌타),배영초-마산중-마산고-동아대-SK-상무-SK,6000만원,0.777000
168,315,최주환,2016,두산,0.281,85,160,21,45,11,...,10,0.424000,0.370000,7,178cm/73kg,1988년 02월 28일,내야수(우투좌타),학강초-광주동성중-광주동성고-두산-상무,6000만원,0.794000
169,316,최준석,2016,롯데,0.262,116,325,49,85,10,...,24,0.430000,0.364000,1,187cm/130kg,1983년 02월 15일,내야수(우투우타),칠성초-포철중-포철공고-(영남사이버대)-롯데-두산-롯데,3000만원,0.794000
170,317,최진행,2016,한화,0.329,28,70,4,23,2,...,3,0.539000,0.375000,1,188cm/100kg,1985년 08월 17일,외야수(우투우타),서울동원초-청량중-덕수정보고-(우송대)-한화-경찰,10000만원,0.914000
171,319,최형우,2016,삼성,0.376,138,519,99,195,46,...,15,0.576000,0.450000,4,180cm/106kg,1983년 12월 16일,외야수(우투좌타),진북초-전주동중-전주고-삼성-경찰-삼성,5000만원,1.026000
172,324,하주석,2016,한화,0.279,115,405,58,113,21,...,6,0.440000,0.328000,9,184cm/84kg,1994년 02월 25일,내야수(우투좌타),강남초-덕수중-신일고-한화-상무,30000만원,0.768000
173,325,하준호,2016,KT,0.219,94,187,26,41,5,...,3,0.337000,0.311000,8,174cm/78kg,1989년 04월 29일,외야수(좌투좌타),하단초-대동중-경남고-롯데,16000만원,0.648000
174,326,한동민,2016,SK,0.278,6,18,3,5,0,...,8,0.614000,0.396000,5,190cm/95kg,1989년 08월 09일,외야수(우투좌타),중앙초(해운대리틀)-대천중-경남고-경성대-SK-상무,3000만원,1.010000
175,329,한승택,2016,KIA,0.179,27,28,1,5,0,...,1,0.277000,0.289000,2,174cm/83kg,1994년 06월 21일,포수(우투우타),잠전초(남양주리틀)-잠신중-덕수고-한화-경찰,9000만원,0.566000
176,331,허경민,2016,두산,0.286,144,538,96,154,24,...,15,0.347000,0.327000,5,176cm/69kg,1990년 08월 26일,내야수(우투우타),송정동초-충장중-광주제일고-두산-경찰,13000만원,0.674000
177,332,허도환,2016,한화,0.218,48,78,9,17,8,...,2,0.375000,0.326000,0,176cm/87kg,1984년 07월 31일,포수(우투우타),서울학동초-이수중-서울고-단국대-두산-넥센-한화,NaN,0.701000
178,337,홍재호,2016,KIA,0.077,22,13,4,1,0,...,0,NaN,NaN,0,180cm/79kg,1987년 05월 10일,내야수(우투우타),부산대연초-대천중-부산고-고려대-KIA-경찰,4000만원,NaN
179,339,황목치승,2016,LG,0.179,48,39,7,7,3,...,0,0.206897,0.258065,4,NaN,1985년 06월 21일,NaN,제주남초-제주제일중-일본 교토고쿠사이고-일본 아세아대,NaN,0.464961
180,341,황윤호,2016,NC,0.083,33,12,7,1,0,...,0,0.267000,0.235000,1,177cm/78kg,1993년 09월 22일,내야수(우투우타),수주초-신월중-장충고-NC-경찰-NC,3000만원,0.502000
181,344,황진수,2016,롯데,0.000,11,10,2,0,0,...,2,0.402000,0.359000,4,181cm/82kg,1989년 02월 15일,내야수(우투양타),석천초-대헌중-공주고,4000만원,0.761000

In [207]:
dtrain = xgb.DMatrix('out16.csv?format=csv&label_column=0')
dtest = xgb.DMatrix('out17.csv?format=csv&label_column=0')

[20:36:31] 214x29 matrix with 6205 entries loaded from out16.csv?format=csv&label_column=0
[20:36:32] 218x29 matrix with 6321 entries loaded from out17.csv?format=csv&label_column=0

In [208]:
dtrain = xgb.DMatrix(data, label=label, missing=-999.0)

In [209]:
w = np.random.rand(5, 1)
dtrain = xgb.DMatrix(data, label=label, missing=-999.0, weight=w)

In [210]:
param = {'max_depth': 2, 'eta': 1, 'silent': 1, 'objective': 'binary:logistic'}
param['nthread'] = 4
param['eval_metric'] = 'auc'

In [211]:
param['eval_metric'] = ['auc', 'ams@0']

In [212]:
evallist = [(dtest, 'eval'), (dtrain, 'train')]

In [186]:
num_round = 10
bst = xgb.train(param, dtrain, num_round, evallist)

ValueError: feature_names mismatch: ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9'] ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28']
training data did not have the following fields: f23, f15, f28, f10, f21, f25, f11, f12, f22, f20, f27, f26, f18, f16, f24, f14, f17, f13, f19